name: Build APK Simple

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm install
    
    - name: Install EAS CLI
      run: npm install -g @expo/eas-cli
    
    - name: Build APK
      run: eas build --platform android --profile production --non-interactive
    
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: har-ghar-munga-apk
        path: |
          *.apk
          *.aab 